export const HOME_SCREEN = "HOME_SCREEN";
export const LOGIN_SCREEN = "LOGIN_SCREEN";
export const WELCOME_SCREEN = "WELCOME_SCREEN";

export const SIGN_UP_SCREEN = "SIGN_UP_SCREEN";
export const SIGN_UP_CONTACT_SCREEN = "SIGN_UP_CONTACT_SCREEN";
export const SIGN_UP_ADDRESS_SCREEN = "SIGN_UP_ADDRESS_SCREEN";
export const SIGN_UP_TERMS_SCREEN = "SIGN_UP_ADDRESS_TERMS_SCREEN";
